name: deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: deploy the site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: deploy
        uses: actions/deploy-pages@v4
